### ISSUE TITLE
There's no file called websocket_tester.py

### ISSUE THREAD

**Issue by sbrl** [owwlo/WebSocketCommandline#1]
I got this working once and it helped me bugfix my websockets server (thanks :D), but I can't do it a second time. For starters, there isn't  a `websocket_tester.py` as mentioned in the readme, and the pip version doesn't even install.

**Comment by owwlo** [comment]
Hey! Thanks for letting me know. This issue report is so meaningful to me. I guess it's so goooooooood to know your project is being used by someone. I started the project purely because A. I didn't find a similar handy tool for my purpose at that time, and B. learn to post a tool to pypi is cool! I guess on the second purpose, I didn't do a good job... lazy me😭. The problem you mentioned is fixed now(pip install WebSocketCommandline + &> websocket_tester). I also have updated the README.md to put the latest usage there. Please have a try and let me know if there is any other issue. Thanks again!

**Comment by sbrl** [comment]
Hey there! You wouldn't believe it, but this only showed up in my GitHub notifications just recently! I have no idea what's going on. If I'd know you replied I would have replied sooner!

Anyway, thanks so much for fixing this! I'll be sure to use it in future. For context, said websockets implementation is my C♯ project the [Gliding Squirrel](https://www.nuget.org/packages/GlidingSquirrel/0.7.1-alpha).
